# Generated by Django 5.0.4 on 2024-05-03 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('HERRAMIENTAS', 'Herramientas'), ('Construcción', 'Construcción'), ('FERRETERIA_GRAL', 'Ferretería general'), ('ELECTRICIDAD', 'Electricidad'), ('FONTANERIA', 'Fontanería'), ('JARDIN', 'Jardin')], max_length=16)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
