# Generated by Django 5.0.4 on 2024-05-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_posts',
            field=models.ManyToManyField(blank=True, related_name='related_by', to='posts.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('cancelled', 'Cancelado'), ('completed', 'Finalizado')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tools', 'Herramientas'), ('construction', 'Construcción'), ('general_hardware_store', 'Ferretería general'), ('electrical', 'Electricidad'), ('plumbing', 'Fontanería'), ('gardens', 'Jardin')], max_length=22),
        ),
    ]
