# Generated by Django 5.0.4 on 2024-05-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_related_posts_post_status_alter_post_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('cancelled', 'Cancelado'), ('completed', 'Finalizado')], default='available', editable=False, max_length=20),
        ),
    ]
