# Generated by Django 5.0.4 on 2024-05-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_related_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('completed', 'Finalizado')], default='available', editable=False, max_length=20),
        ),
    ]
