# Generated by Django 5.0.4 on 2024-05-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_image_imagepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
