# Generated by Django 4.2.13 on 2024-05-08 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_manufacturing_date_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='post',
            field=models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post'),
        ),
    ]
