# Generated by Django 4.2.13 on 2024-05-08 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('posts', '0009_alter_imagepost_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
    ]
