# Generated by Django 4.2.13 on 2024-05-08 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('posts', '0010_post_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
    ]
