# Generated by Django 4.2.13 on 2024-05-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='manufacturing_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('completed', 'Finalizado'), ('paused', 'Pausado')], default='available', editable=False, max_length=20),
        ),
    ]
