# Generated by Django 4.2.13 on 2024-05-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_post_manufacturing_date_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('completed', 'Finalizado'), ('paused', 'Pausado')], default='available', max_length=20),
        ),
    ]
