# Generated by Django 4.2.13 on 2024-05-11 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('posts', '0014_alter_post_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
    ]
