# Generated by Django 4.2.13 on 2024-05-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original_branch_id',
            field=models.IntegerField(null=True),
        ),
    ]
