# Generated by Django 5.0.4 on 2024-05-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
