# Generated by Django 5.0.4 on 2024-06-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_package_post_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(choices=[('none', 'Ninguno'), ('bronce', 'Bronce'), ('plata', 'Plata'), ('oro', 'Oro')], default='none', max_length=10, unique=True),
        ),
    ]
