# Generated by Django 5.0.4 on 2024-06-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_alter_package_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(choices=[('4_none', 'Ninguno'), ('3_bronce', 'Bronce'), ('2_plata', 'Plata'), ('1_oro', 'Oro')], default='4_none', max_length=10, unique=True),
        ),
    ]
