# Generated by Django 5.0.4 on 2024-06-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_alter_package_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='priority',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(choices=[('none', 'Ninguno'), ('bronce', 'Bronce'), ('plata', 'Plata'), ('oro', 'Oro')], default='none', max_length=10, unique=True),
        ),
    ]
