# Generated by Django 5.0.4 on 2024-06-20 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_packagepurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagepurchase',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.package', verbose_name='Paquete'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='Publicación'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
