# Generated by Django 5.0.4 on 2024-06-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_alter_packagepurchase_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deletion_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Razón de eliminación'),
        ),
    ]
