# Generated by Django 5.0.6 on 2024-06-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_alter_package_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(choices=[('none', 'Ninguno'), ('bronce', 'Bronce'), ('plata', 'Plata'), ('oro', 'Oro')], default='none', max_length=10, unique=True),
        ),
    ]
