# Generated by Django 5.0.4 on 2024-06-28 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_post_deletion_reason'),
        ('posts', '0030_alter_package_name'),
    ]

    operations = [
    ]
