# Generated by Django 5.0.4 on 2024-06-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_product_main_image_alter_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
