# Generated by Django 5.0.4 on 2024-05-24 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0006_branch_is_active'),
        ('posts', '0016_post_original_branch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('requested', 'Solicitado'), ('accepted', 'Aceptado'), ('committed', 'Finalizado'), ('cancelled', 'Cancelado')], default='requested', max_length=20)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barter_branch', to='branches.branch')),
                ('requested_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_barters', to='posts.post')),
                ('requesting_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requesting_barters', to='posts.post')),
            ],
        ),
    ]
