# Generated by Django 5.0.4 on 2024-05-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barter',
            name='state',
            field=models.CharField(choices=[('requested', 'Solicitado'), ('accepted', 'Aceptado'), ('committed', 'Finalizado'), ('cancelled', 'Cancelado'), ('parcial_accepted', 'Parcialmente Aceptado')], default='requested', max_length=20),
        ),
    ]
