# Generated by Django 5.0.4 on 2024-05-30 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_employeeuser_email'),
        ('barter', '0002_alter_barter_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='barter',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barter_employee', to='accounts.employeeuser'),
        ),
    ]
