# Generated by Django 5.0.4 on 2024-06-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0003_barter_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='barter',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
