# Generated by Django 5.0.4 on 2024-06-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0004_barter_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='barter',
            name='finished_date',
            field=models.DateField(null=True),
        ),
    ]
