# Generated by Django 5.0.4 on 2024-07-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='ferreplus@gmail.com', max_length=254),
        ),
    ]
