# Generated by Django 5.0.4 on 2024-06-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarouselbanner',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='homecarouselbanner',
            name='title',
            field=models.CharField(default='imagen_banner', max_length=100),
        ),
    ]
