# Generated by Django 5.0.4 on 2024-05-09 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dni',
        ),
    ]
