# Generated by Django 5.0.4 on 2024-05-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dni',
        ),
    ]
