# Generated by Django 5.0.4 on 2024-05-23 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_groups_and_more'),
        ('branches', '0005_alter_branch_unique_together_alter_branch_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='branches.branch'),
        ),
    ]
