# Generated by Django 5.0.4 on 2024-05-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_employeeuser_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='employeeuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='employeeuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='employeeuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employeeuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employeeuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employeeuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='employeeuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='employeeuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='employeeuser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
