# Generated by Django 5.0.4 on 2024-05-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_employeeuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
