# Generated by Django 5.0.4 on 2024-06-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_employeeuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
    ]
