# Generated by Django 5.0.4 on 2024-05-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
