# Generated by Django 5.0.4 on 2024-05-12 19:32

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
