# Generated by Django 5.0.4 on 2024-05-12 21:40

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_alter_branch_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'invalid': 'Por favor, introduce un número de teléfono válido.'}, help_text='  Formato: +54 12345678', max_length=128, region=None),
        ),
    ]
