# Generated by Django 5.0.4 on 2024-05-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_alter_branch_unique_together_alter_branch_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
