# Generated by Django 5.0.4 on 2024-05-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnproposal',
            name='time',
        ),
        migrations.AddField(
            model_name='turnproposal',
            name='end_time',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='turnproposal',
            name='start_time',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
