# Generated by Django 5.0.4 on 2024-06-01 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0003_barter_employee'),
        ('turns', '0002_remove_turnproposal_time_turnproposal_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('barter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='barter.barter')),
            ],
        ),
    ]
