# Generated by Django 5.0.4 on 2024-06-01 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0003_barter_employee'),
        ('turns', '0003_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='barter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barter.barter'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.TextField(),
        ),
    ]
