# Generated by Django 5.0.4 on 2024-06-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0003_barter_employee'),
        ('turns', '0004_alter_report_barter_alter_report_reason'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='CancellationReport',
        ),
    ]
